field: 8fee31db-d190-4758-b1e3-f9a7420aa68a # Article Body
fieldLayouts:
  0bd133c6-8a5c-4da2-a689-124cd4f35b1a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1943ce5d-58b3-45ca-b9c3-aae2a6d73130 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9039417c-c093-4a85-af41-eb6a0c9d9dc2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ce938455-0bbc-4f7b-ba37-788c322396c0
        userCondition: null
fields:
  1943ce5d-58b3-45ca-b9c3-aae2a6d73130: # Heading
    columnSuffix: uqezzqmi
    contentColumnType: string(1020)
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: 255
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: heading
name: Heading
sortOrder: 2
