field: 8fee31db-d190-4758-b1e3-f9a7420aa68a # Article Body
fieldLayouts:
  ad9f2509-36fe-49a0-a45d-7cb1d9e90c81:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5a236b1b-00c7-4038-9264-b4e97830be5f # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53a72f01-7639-44a1-a7c0-d54c3ec153b0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1ee0eb29-ceaf-45d6-b31d-d4335d7d001c # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f491488e-41a5-42f6-81e5-86682f34ff99
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 942f10b8-e7c1-4108-9fc2-c0b240787526 # Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50a3a363-0652-4d56-8bde-f13a08e5ed49
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a9cda519-3ae0-44c1-92a6-680dde1e5027
        userCondition: null
fields:
  1ee0eb29-ceaf-45d6-b31d-d4335d7d001c: # Caption
    columnSuffix: snpssndc
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: null
    name: Caption
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  5a236b1b-00c7-4038-9264-b4e97830be5f: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:2c6e9955-32e0-4310-bb8b-8bddb9d83e2f' # Assets
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:2c6e9955-32e0-4310-bb8b-8bddb9d83e2f' # Assets
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      source: null
      sources:
        - 'volume:2c6e9955-32e0-4310-bb8b-8bddb9d83e2f' # Assets
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  942f10b8-e7c1-4108-9fc2-c0b240787526: # Position
    columnSuffix: ouedvvhm
    contentColumnType: string
    fieldGroup: null
    handle: position
    instructions: null
    name: Position
    searchable: true
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Center
            -
              - value
              - center
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Full
            -
              - value
              - full
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: image
name: Image
sortOrder: 5
