field: 8fee31db-d190-4758-b1e3-f9a7420aa68a # Article Body
fieldLayouts:
  f4f2f9b7-260d-4fc5-9a82-1fcacbfc512f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 60d2ec68-884d-4556-93c7-059ae103830c # Quote
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40b3bb4e-5fed-4c5e-9069-d413bddaa9a1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 789299f8-0aeb-4555-8ceb-6b8f9a027268 # Attribution
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1b9aa8c-4b6a-47c5-b910-404351c22dd2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4bf0c4ac-93f4-4124-a602-acf797318279 # Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c7d5aca-267c-4dd6-853f-d48019a8dff1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9a41b5ff-afe8-40b9-b21d-aef10758533f
        userCondition: null
fields:
  4bf0c4ac-93f4-4124-a602-acf797318279: # Position
    columnSuffix: dlvemyui
    contentColumnType: string
    fieldGroup: null
    handle: position
    instructions: null
    name: Position
    searchable: true
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Center
            -
              - value
              - center
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Full
            -
              - value
              - full
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  60d2ec68-884d-4556-93c7-059ae103830c: # Quote
    columnSuffix: ufnodjav
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: null
    name: Quote
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  789299f8-0aeb-4555-8ceb-6b8f9a027268: # Attribution
    columnSuffix: rzxtexda
    contentColumnType: text
    fieldGroup: null
    handle: attribution
    instructions: null
    name: Attribution
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: quote
name: Quote
sortOrder: 7
