field: 8fee31db-d190-4758-b1e3-f9a7420aa68a # Article Body
fieldLayouts:
  4dda3694-1544-44fd-bd77-5fb9cc27e607:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 54074c51-7ba2-4505-82f3-b87fe64290e6 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f622dd3-3d3f-43c1-a273-8fc274aae7b8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c7558099-aeb6-4dae-acad-adea485ea6df # Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2bf39068-5cf6-4695-9109-412e6a88171f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 336284b0-c5cb-4ec6-a157-eb0f35a7d838
        userCondition: null
fields:
  54074c51-7ba2-4505-82f3-b87fe64290e6: # Text
    columnSuffix: cwwaqfyp
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  c7558099-aeb6-4dae-acad-adea485ea6df: # Position
    columnSuffix: dyezfneq
    contentColumnType: string
    fieldGroup: null
    handle: position
    instructions: null
    name: Position
    searchable: true
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Center
            -
              - value
              - center
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: text
name: Text
sortOrder: 3
