fieldLayouts:
  bc57fee0-8843-4327-8dbc-68030f642d20:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 508fa209-e1e5-4130-90cf-bfaab8290f6d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 65b71133-c775-443f-a596-5eb3f5b0c8ec
        userCondition: null
fs: siteAssets
handle: siteAssets
name: 'Site Assets'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: siteAssets
transformSubpath: ''
