columnSuffix: null
contentColumnType: string
fieldGroup: d527ecd7-601c-4525-9238-9d4b0c7d299c # Common
handle: featuredImage
instructions: null
name: 'Featured Image'
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:2c6e9955-32e0-4310-bb8b-8bddb9d83e2f' # Site Assets
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: 2
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:2c6e9955-32e0-4310-bb8b-8bddb9d83e2f' # Site Assets
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  source: null
  sources:
    - 'volume:2c6e9955-32e0-4310-bb8b-8bddb9d83e2f' # Site Assets
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
