on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - production

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: codecov/codecov-action@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npx prettier --check .
      - name: Discord Success
        if: ${{ success() }}
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#00ff00"
          message: |
            Job Succeeded 🧘
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Discord Failure
        if: ${{ failure() }}
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#FF0000"
          message: |
            Job Failed 🫠
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2
          ini-values: post_max_size=256M, max_execution_time=180, memory_limit=512M
          extensions: ctype,curl,dom,iconv,imagick,intl,json,mbstring,openssl,pcre,pdo,reflection,spl,zip
      - name: Require Forge CLI
        run: composer global require laravel/forge-cli
      - name: Deploy Site
        run: |
          forge server:switch hidden-firefly
          forge deploy applefakenews.com
          forge command applefakenews.com --command="php craft migrate/all --no-content --interactive=0"
          forge command applefakenews.com --command="php craft project-config/apply"
          forge command applefakenews.com --command="php craft migrate --track=content --interactive=0"
        env:
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
      - uses: lhansford/bugsnag-report-build-action@v1.1.0
        name: Report Build to Bugsnag
        with:
          appVersion: ${{ github.event.repository.updated_at }}
          apiKey: ${{ secrets.BUGSNAG_API_KEY }}
  e2e:
    needs: deploy
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
