on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: prettier --check .
      - name: Notification
        if: ${{ always() }}
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: Build [${{ job.status }}]
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
