name: Notification on push

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: shinybrad
          DISCORD_AVATAR: https://raw.githubusercontent.com/craftcms/automation-workshop/production/web/assets/shinybrad.png
