name: Notification on push

on:
  workflow_dispatch:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Message Notify
        uses: appleboy/discord-action@0.0.3
        with:
          color: "#ff0000"
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: ${{ github.repository }} deployed to ${{ github.ref_name }}
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
