name: Notification on push

on:
  workflow_dispatch:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "{{ EVENT_PAYLOAD.repository.full_name }} has been deployed to {{ github.head_ref }}."
